# Generated by Django 6.0.7 on 2026-08-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_phone', models.CharField(max_length=15)),
                ('sender_address', models.TextField()),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=15)),
                ('receiver_address', models.TextField()),
                ('parcel_type', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Booked', max_length=30)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
